#!/usr/bin/env python3
"""Check the documentation's factual claims against the codebase.

Three classes of claim are machine-checkable, and all three have been wrong in
this repo before:

1. identifiers  — a named function/module must exist
2. return keys  — a documented dict key must be in the actual return
3. config names — a named parameter must exist in the active study

Numbers are NOT checked here; they are generated by docs/_tools/worked_values.py
and pasted in, so a stale number shows up as a diff in that script's output
rather than as a silent inaccuracy.

Run from the repo root:  python docs/_tools/verify_docs.py
Exit 0 = clean, 1 = findings.
"""
from __future__ import annotations
import ast
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"

# Names that look like project functions but are stdlib, third-party or local
# variables inside an example. Kept explicit so the check stays honest.
IGNORE = {
    "print", "range", "len", "append", "format", "array", "figure", "subplots",
    "plot", "legend", "zeros", "ones", "linspace", "logspace", "sqrt", "exp",
    "log", "log10", "abs", "round", "enumerate", "items", "update", "copy",
    "keys", "values", "join", "sum", "max", "min", "sort", "sorted", "float",
    "int", "str", "dict", "list", "tuple", "set", "bool", "isinstance",
    "brentq", "root_scalar", "linregress", "lognorm", "percentile", "reload",
    "lower", "upper", "startswith", "endswith", "strip", "split", "replace",
    "get", "setdefault", "pop", "extend", "insert", "index", "count",
    "savefig", "show", "tight_layout", "loglog", "semilogy", "semilogx",
    "scatter", "axhline", "axvline", "text", "annotate", "colorbar", "imshow",
    "set_xlabel", "set_ylabel", "set_title", "set_xlim", "set_ylim", "grid",
    "astype", "reshape", "mean", "std", "isfinite", "isnan", "where",
    "argmax", "argmin", "sample", "analyze", "read_csv", "to_csv", "DataFrame",
    "fit_transform", "sort_values", "tolist", "nanmax", "nanmin", "median",
    "deepcopy", "warn", "simplefilter", "arange", "column_stack", "ptp",
    "default_rng", "uniform", "makedirs", "exists", "dirname", "basename",
    "globals", "locals", "vars", "getattr", "setattr", "hasattr", "type",
    "repr", "open", "iter", "next", "zip", "map", "filter", "any", "all",
    "super", "id", "hash", "divmod", "pow", "bin", "hex", "chr", "ord",
}


def real_names() -> tuple[set[str], set[str]]:
    """(functions, modules) that actually exist under calculations/."""
    funcs, mods = set(), set()
    for p in sorted((ROOT / "calculations").rglob("*.py")):
        rel = p.relative_to(ROOT)
        dotted = str(rel.with_suffix("")).replace("/", ".")
        # an __init__.py IS its package, not a `pkg.__init__` submodule
        mods.add(dotted[: -len(".__init__")] if dotted.endswith(".__init__")
                 else dotted)
        for n in ast.walk(ast.parse(p.read_text())):
            if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)):
                funcs.add(n.name)
    return funcs, mods


def config_names() -> set[str]:
    """Parameter names available from the active study."""
    sys.path.insert(0, str(ROOT))
    import warnings
    warnings.simplefilter("ignore")
    from calculations.config import model_config as mc
    names = set()
    for attr in ("DEFAULT_PARAMS_LEVEL5", "DEFAULT_PARAMS_LEVEL5L6",
                 "METALS", "OXIDES", "CONDITIONS", "MICROSTRUCTURE",
                 "OXIDE_DEFECTS"):
        v = getattr(mc, attr, None)
        if isinstance(v, dict):
            names |= set(map(str, v))
    return names


def doc_pages() -> list[pathlib.Path]:
    skip = {"_build", "_tools", "_static", ".mplcache", "_source_material"}
    return [p for p in sorted(DOCS.rglob("*.md"))
            if not any(s in p.parts for s in skip)]


def main() -> int:
    funcs, mods = real_names()
    cfg = config_names()
    findings: list[str] = []

    fn_ref  = re.compile(r'`([a-z_][a-z0-9_]{3,})\(')          # `name(
    mod_ref = re.compile(r'`(calculations\.[a-z_][a-z0-9_.]*)`')
    # Project-convention names: these prefixes are ours, so a call to one that
    # does not exist is a broken example even inside a code fence.
    proj_ref = re.compile(
        r'\b((?:calculate|solve|classify|assign|compute|build|run|get|plot|'
        r'sieverts|fick|trap|grain|gb|vacancy|combined|arrhenius|presets|size)'
        r'_[a-z0-9_]+)\s*\(')

    for page in doc_pages():
        txt = page.read_text()
        rel = page.relative_to(ROOT)

        # A page may deliberately name something that does not exist — e.g. to
        # warn that an inherited design note referenced a phantom function.
        # Declare those with an HTML comment so the check stays strict elsewhere:
        #     <!-- verify-docs: allow calculate_full_system_flux -->
        allowed = set()
        for decl in re.findall(r'<!--\s*verify-docs:\s*allow\s+([^>]+?)\s*-->', txt):
            allowed |= {n.strip() for n in decl.replace(",", " ").split()}

        called = set(fn_ref.findall(txt)) | set(proj_ref.findall(txt))
        for name in sorted(called):
            if name in IGNORE or name in funcs or name in allowed:
                continue
            findings.append(f"{rel}: `{name}()` does not exist")

        for name in sorted(set(mod_ref.findall(txt))):
            if name not in mods:
                findings.append(f"{rel}: module `{name}` does not exist")

        # a repo-relative link to a source file breaks in HTML; must be absolute
        for tgt in re.findall(r'\]\((?!http|#|mailto)([^)]+)\)', txt):
            if tgt.endswith((".py", ".toml", ".tex", ".bib", ".lock", ".txt")):
                findings.append(f"{rel}: relative source link '{tgt}' — use an absolute github URL")

    findings = sorted(set(findings))

    if findings:
        print(f"{len(findings)} finding(s):\n")
        for f in findings:
            print(f"  {f}")
        return 1
    print(f"clean — checked {len(doc_pages())} pages against "
          f"{len(funcs)} functions, {len(mods)} modules, {len(cfg)} config names")
    return 0


if __name__ == "__main__":
    sys.exit(main())
