#!/bin/bash
# Regenerate requirements.lock.txt inside the exact production platform and
# interpreter. Resolving on the macOS dev host would produce a lock with the
# wrong platform-specific wheels, so this must run in the container.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PY_TAG="${PY_TAG:-3.12-slim}"
PLATFORM="${PLATFORM:-linux/amd64}"

docker run --rm --platform "$PLATFORM" -v "$HERE:/req" -w /req \
  "python:$PY_TAG" sh -eux -c '
    python -m pip install --quiet --upgrade pip
    python -m pip install --quiet --no-cache-dir -r requirements.in
    python -m pip check
    {
      echo "# GENERATED by container/lock.sh -- do not hand-edit."
      echo "# python:'"$PY_TAG"' on '"$PLATFORM"'"
      python -m pip freeze --exclude-editable
    } > requirements.lock.txt
  '
echo "wrote $HERE/requirements.lock.txt ($(grep -vc '^#' "$HERE/requirements.lock.txt") pinned packages)"
